---
title: 'STAT 231: Problem Set 8A'
author: "Kim Zhou"
date: "due by 10 PM on Monday, May 3"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

In order to most effectively digest the textbook chapter readings -- and the  new R commands each presents -- series A homework assignments are designed to encourage you to read the textbook chapters actively and in line with the textbook's Prop Tip of page 33:

"\textbf{Pro Tip}: If you want to learn how to use a particular command, we highly recommend running the example code on your own" 

A more thorough reading and light practice of the textbook chapter prior to class allows us to dive quicker and deeper into the topics and commands during class.  Furthermore, learning a programming language is like learning any other language -- practice, practice, practice is the key to fluency.  By having two assignments each week, I hope to encourage practice throughout the week.  A little coding each day will take you a long way!

*Series A assignments are intended to be completed individually.*  While most of our work in this class will be collaborative, it is important each individual completes the active readings.  The problems should be straightforward based on the textbook readings, but if you have any questions, feel free to ask me!

Steps to proceed:

\begin{enumerate}
\item In RStudio, go to File > Open Project, navigate to the folder with the course-content repo, select the course-content project (course-content.Rproj), and click "Open" 
\item Pull the course-content repo (e.g. using the blue-ish down arrow in the Git tab in upper right window)
\item Copy ps8A.Rmd from the course repo to your repo (see page 6 of the GitHub Classroom Guide for Stat231 if needed)
\item Close the course-content repo project in RStudio
\item Open YOUR repo project in RStudio
\item In the ps8A.Rmd file in YOUR repo, replace "YOUR NAME HERE" with your name
\item Add in your responses, committing and pushing to YOUR repo in appropriate places along the way
\item Run "Knit PDF" 
\item Upload the pdf to Gradescope.  Don't forget to select which of your pages are associated with each problem.  \textit{You will not get credit for work on unassigned pages (e.g., if you only selected the first page but your solution spans two pages, you would lose points for any part on the second page that the grader can't see).} 
\end{enumerate}

```{r, setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```


\newpage
# 1.  "Tell the truth. Don't steal. Don't harm innocent people."

In the textbook, the authors state, "Common sense is a good starting point for evaluating the ethics of a situation.  Tell the truth.  Don't steal.  Don't harm innocent people.  But, professional ethics also require a neutral, unemotional, and informed assessment."

(1a) Assuming the numbers reported in Figure 6.1 are correct (truthful), do you think Figure 6.1 is an *unethical* representation of the data presented?  Why or why not?

> ANSWER: The y-axis in figure 6.1 is inverted so that the highest values are at the bottom where we normally and intuitively expect the smallest value. Thus, at first glance, the graph appears to tell us that the number of nurders committed using firearms decreased after the law was enacted. But, taking into account the inverted axis, the data is actually saying that deaths by firearms increased after the law was passed. This is unethical because the creators of the graph manipulated the visualization to be misleading and support their agenda. 

(1b) Pulling from the examples in the textbook, provide one example of a more nuanced ethical situation (one that you perhaps found surprising or hadn't considered before).

> ANSWER: Example 6.3.5 surprised me because, in general, we assume everything approved by the FDA has gone through rigorous testing and evaluation, but the report with the MI danger of Vioxx was missed for many years. It seems that the way those findings were reported could have contributed to this. The blurb used "lower" to describe MI rate, however, where we normally would see "in Vioxx groups" since that is what we are testing and comparing against the standard, we instead see lower in standard group. Without careful reading, this would be very misleading and it then thought that Vioxx had lower MI risk, which is incorrect.

\newpage
# 2. Does publishing a flawed analysis raise ethical questions? 

In the course so far, we've touched upon some of the ethical considerations discussed in this chapter, including ethical acquisition of data (e.g., abiding by the scraping rules of a given website) and reproducibility.  At the end of Section 6.3.4 (the "Reproducible spreadsheet analysis" example), the authors ask: Does publishing a flawed analysis raise ethical questions?

After reading Section 6.4.1 ("Applying the precepts") for the "Reproducible spreadsheet analysis" example, re-consider that question: Does publishing a flawed analysis raise ethical questions?  And, a follow-up question for consideration: Does it depend on who published the flawed analysis (e.g., a trained data scientist? an economist who conducts data science work?  a psychologist who works with data? a clinician who dabbles in data science?)

In 4-6 sentences, respond to those questions and explain your response.   

> ANSWER: According to the textbook, it is not an ethical obligation to reach correct research results, but rather do any and everything to make sure the data and framework of analysis are truthfully reflecting the data. Therefore, publishing a flawed analysis doesn't necessarily violate ethics as long as the data was represented truthfully. However, if the data was not publishied properly and truthfully, then I don't think it matters who published the flawed analysis. Any data and analysis published will have important ramifications that extend past the researchers so those conducting the analyses must be diligent and careful when analyzing because they will have an impact on other people's lives. Obviously some will have influece more or fewer lives, but one way or the other, it will impact others outside of the scientific community and many wthin it.

